/*
 * K3 System Firmware Resource Management Configuration Data
 * Auto generated from K3 Resource Partitioning tool
 *
 * Copyright (C) 2019-2021 Texas Instruments Incorporated - https://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "common.h"
#include <hosts.h>
#include <devices.h>
#include <resasg_types.h>

const struct boardcfg_tifs_rm_local j784s4_boardcfg_rm_data = {
	.rm_boardcfg = {
		/* boardcfg_abi_rev */
		.rev = {
			.boardcfg_abi_maj = 0x0,
			.boardcfg_abi_min = 0x1,
		},

		/* boardcfg_rm_host_cfg */
		.host_cfg = {
			.subhdr = {
				.magic = BOARDCFG_RM_HOST_CFG_MAGIC_NUM,
				.size = sizeof (struct boardcfg_rm_host_cfg),
			},
			.host_cfg_entries = {
				{
					.host_id = HOST_ID_MCU_0_R5_0,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MCU_0_R5_2,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_A72_2,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_A72_3,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_C7X_0_1,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_C7X_1_1,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_C7X_2_1,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_C7X_3_1,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MAIN_0_R5_0,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MAIN_0_R5_2,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MAIN_1_R5_0,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MAIN_1_R5_2,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MAIN_2_R5_0,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
				{
					.host_id = HOST_ID_MAIN_2_R5_2,
					.allowed_atype = 0b101010,
					.allowed_qos = 0xAAAA,
					.allowed_orderid = 0xAAAAAAAA,
					.allowed_priority = 0xAAAA,
					.allowed_sched_priority = 0xAA,
				},
			}
		},

		/* boardcfg_rm_resasg */
		.resasg = {
			.subhdr = {
				.magic = BOARDCFG_RM_RESASG_MAGIC_NUM,
				.size = sizeof (struct boardcfg_rm_resasg),
			},
			.resasg_entries_size =
				BOARDCFG_TIFS_RM_RESASG_ENTRIES *
				sizeof (struct boardcfg_rm_resasg_entry),
			.reserved = 0,
			/* .resasg_entries is set via boardcfg_rm_local */
		},
	},

	/* This is actually part of .resasg */
	.resasg_entries = {
		/* Main GPIO Interrupt router */
		/* Not Applicable for TIFS */
		/* Compare event Interrupt router */
		/* Not Applicable for TIFS */
		/* Main 2 MCU Level Interrupt router */
		/* Not Applicable for TIFS */
		/* Main 2 MCU Pulse Interrupt router */
		/* Not Applicable for TIFS */
		/* Timesync Interrupt router */
		/* Not Applicable for TIFS */
		/* Wakeup GPIO Interrupt router */
		/* Not Applicable for TIFS */
		/* Main NAVSS Block Copy DMA Global event trigger */
		/* Not Applicable for TIFS */
		/* Main NAVSS Block Copy DMA Global config */
		/* Not Applicable for TIFS */
		/* Main NAVSS Block Copy DMA Rings for Split TR RX channels */
		{
			.start_resource = 16,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_RING_SPLIT_TR_RX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 32,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_RING_SPLIT_TR_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Block Copy DMA Rings for Split TR TX channels */
		{
			.start_resource = 0,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_RING_SPLIT_TR_TX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 8,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_RING_SPLIT_TR_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Block Copy DMA Split TR Rx channels */
		{
			.start_resource = 0,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_SPLIT_TR_RX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 16,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_SPLIT_TR_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Block Copy DMA Split TR Tx channels */
		{
			.start_resource = 0,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_SPLIT_TR_TX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 8,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_BCDMA_0,
					RESASG_SUBTYPE_BCDMA_SPLIT_TR_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Interrupt router */
		/* Not Applicable for TIFS */
		/* MODSS Interrupt aggregator0 Virtual interrupts */
		{
			.start_resource = 0,
			.num_resource = 64,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_MODSS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_ALL,
		},
		/* MODSS Interrupt aggregator0 Global events */
		/* Not Applicable for TIFS */
		/* MODSS Interrupt aggregator1 Virtual interrupts */
		{
			.start_resource = 0,
			.num_resource = 64,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_MODSS_INTA_1,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_ALL,
		},
		/* MODSS Interrupt aggregator1 Global events */
		/* Not Applicable for TIFS */
		/* Main NAVSS Non secure proxies */
		{
			.start_resource = 0,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 4,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 8,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 12,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 16,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 20,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 24,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 36,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 40,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 44,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 48,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 52,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 56,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 60,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_PROXY_0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* Main NAVSS Ring accelerator error event config */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_ERROR_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Ring accelerator Free rings */
		{
			.start_resource = 423,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 433,
			.num_resource = 20,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 453,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 469,
			.num_resource = 13,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 482,
			.num_resource = 128,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 610,
			.num_resource = 46,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 656,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 666,
			.num_resource = 20,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 686,
			.num_resource = 64,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 750,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 760,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 764,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 878,
			.num_resource = 128,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 1006,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_A72_3,
		},
		/* Main NAVSS Rings for Normal capacity Rx channels */
		{
			.start_resource = 345,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 351,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 351,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 352,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 353,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 354,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 355,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 359,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 360,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 361,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 362,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 365,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 366,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 367,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 368,
			.num_resource = 25,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 393,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 394,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 396,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 398,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 400,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 402,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 414,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 415,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 417,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 419,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 421,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		/* Main NAVSS Rings for Normal capacity Tx channels */
		{
			.start_resource = 4,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 10,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 10,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 13,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 14,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 18,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 19,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 20,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 21,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 24,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 25,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 26,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 27,
			.num_resource = 25,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 52,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 53,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 55,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 57,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 59,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 61,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 73,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 77,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 79,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 81,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 83,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		/* Main NAVSS Rings for extended Tx channels */
		{
			.start_resource = 85,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 93,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 101,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 107,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 111,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 113,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 115,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 115,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_ALL,
		},
		{
			.start_resource = 117,
			.num_resource = 96,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 213,
			.num_resource = 96,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 309,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_EXT),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		/* Main NAVSS Rings for High capacity Rx channels */
		{
			.start_resource = 343,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX_H),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 344,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX_H),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Rings for Ultra High capacity Rx channels */
		{
			.start_resource = 341,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX_UH),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 342,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_RX_UH),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Rings for High capacity Tx channels */
		{
			.start_resource = 2,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_H),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 3,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_H),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Rings for Ultra High capacity Tx channels */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_UH),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 1,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_UDMAP_TX_UH),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Ring accelerator virt_id range */
		{
			.start_resource = 0,
			.num_resource = 5,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_VIRTID),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 5,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_VIRTID),
			.host_id = HOST_ID_A72_3,
		},
		/* Main NAVSS Ring accelerator ring monitors */
		{
			.start_resource = 0,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 3,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 5,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 8,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 13,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 19,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 22,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 25,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 28,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 29,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 30,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 31,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_RINGACC_0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* Main NAVSS UDMA Rx free flows */
		{
			.start_resource = 82,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 98,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 114,
			.num_resource = 110,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Invalid flow event config */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_INVALID_FLOW_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS UDMA Global event trigger */
		/* Not Applicable for TIFS */
		/* Main NAVSS UDMA Global config */
		/* Not Applicable for TIFS */
		/* Main NAVSS UDMA Normal capacity Rx channels */
		{
			.start_resource = 4,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 10,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 10,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 13,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 14,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 18,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 19,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 20,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 21,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 24,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 25,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 26,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 27,
			.num_resource = 25,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 52,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 53,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 55,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 57,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 59,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 61,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 73,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 74,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 76,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 78,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 80,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		/* Main NAVSS UDMA High capacity Rx channels */
		{
			.start_resource = 2,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_HCHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 3,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_HCHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS UDMA Ultra High capacity Rx channels */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_UHCHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 1,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_UHCHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS UDMA Normal capacity Tx channels */
		{
			.start_resource = 4,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 10,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 10,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 13,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 14,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 18,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 19,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 20,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 21,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 24,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 25,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 26,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 27,
			.num_resource = 25,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 52,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 53,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 55,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 57,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 59,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 61,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 73,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 77,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 79,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 81,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 83,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		/* Main NAVSS UDMA Extended Tx channels */
		{
			.start_resource = 85,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 93,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 101,
			.num_resource = 6,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 107,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 111,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 113,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 115,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 115,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_ALL,
		},
		{
			.start_resource = 117,
			.num_resource = 96,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 213,
			.num_resource = 96,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 309,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_ECHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		/* Main NAVSS UDMA High capacity Tx channels */
		{
			.start_resource = 2,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_HCHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 3,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_HCHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS UDMA Ultra High capacity Tx channels */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_UHCHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 1,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_UHCHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		/* Main NAVSS Interrupt aggregator Virtual interrupts */
		{
			.start_resource = 56,
			.num_resource = 56,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 112,
			.num_resource = 24,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 136,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 148,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 160,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 170,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 180,
			.num_resource = 28,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 208,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 216,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 228,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 236,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 246,
			.num_resource = 10,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		/* Main NAVSS UDMA Interrupt aggregator Global events */
		/* Not Applicable for TIFS */
		/* Main NAVSS Block Copy DMA Tx channel error event */
		{
			.start_resource = 1536,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_BCDMA_TX_CHAN_ERROR_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Block Copy DMA Tx channel data completion event */
		{
			.start_resource = 2048,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_BCDMA_TX_CHAN_DATA_COMPLETION_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Block Copy DMA Tx channel ring completion event */
		{
			.start_resource = 2560,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_BCDMA_TX_CHAN_RING_COMPLETION_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Block Copy DMA Rx channel error event */
		{
			.start_resource = 3072,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_BCDMA_RX_CHAN_ERROR_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Block Copy DMA Rx channel data completion event */
		{
			.start_resource = 3584,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_BCDMA_RX_CHAN_DATA_COMPLETION_OES),
			.host_id = HOST_ID_ALL,
		},
		/* Main NAVSS Block Copy DMA Rx channel ring completion event */
		{
			.start_resource = 4096,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_BCDMA_RX_CHAN_RING_COMPLETION_OES),
			.host_id = HOST_ID_ALL,
		},
		/* MCU NAVSS Interrupt router */
		/* Not Applicable for TIFS */
		/* MCU NAVSS Non secure proxies */
		{
			.start_resource = 1,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 3,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 7,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 11,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 15,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 19,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 23,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 39,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 43,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 47,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 51,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 54,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 56,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 60,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_PROXY0,
					RESASG_SUBTYPE_PROXY_PROXIES),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* MCU NAVSS Ring accelerator error event config */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_ERROR_OES),
			.host_id = HOST_ID_ALL,
		},
		/* MCU NAVSS Ring accelerator Free rings */
		{
			.start_resource = 96,
			.num_resource = 20,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 116,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 124,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 132,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 140,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 148,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 156,
			.num_resource = 16,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 172,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 180,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 188,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 196,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 204,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 208,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 240,
			.num_resource = 12,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_GP),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* MCU NAVSS Rings for Normal capacity Rx channels */
		{
			.start_resource = 50,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 53,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 53,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 54,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 55,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 56,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 57,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 58,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 59,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 60,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 61,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 62,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 63,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 65,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 65,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 73,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 77,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 78,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 79,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 80,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 81,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 83,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 84,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 85,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 86,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 87,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 88,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 91,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* MCU NAVSS Rings for Normal capacity Tx channels */
		{
			.start_resource = 2,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 5,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 5,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 6,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 7,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 8,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 9,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 10,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 13,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 14,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 15,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 17,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 17,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 25,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 29,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 30,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 31,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 32,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 33,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 35,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 36,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 37,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 38,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 39,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 40,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 43,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 45,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX),
			.host_id = HOST_ID_ALL,
		},
		/* MCU NAVSS Rings for High capacity Rx channels */
		{
			.start_resource = 48,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX_H),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 48,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_RX_H),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		/* MCU NAVSS Rings for High capacity Tx channels */
		{
			.start_resource = 0,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX_H),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 0,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_UDMAP_TX_H),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		/* MCU NAVSS Ring accelerator virt_id range */
		{
			.start_resource = 0,
			.num_resource = 5,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_VIRTID),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 5,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_VIRTID),
			.host_id = HOST_ID_A72_3,
		},
		/* MCU NAVSS Ring accelerator ring monitors */
		{
			.start_resource = 0,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 3,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 5,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 7,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 9,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 11,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 13,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 16,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 18,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 20,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 22,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 24,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 26,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 29,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_RINGACC0,
					RESASG_SUBTYPE_RA_MONITORS),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* MCU NAVSS UDMA Rx free flows */
		{
			.start_resource = 48,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 56,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 60,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 68,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 72,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 76,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 80,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 82,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 84,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 92,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_FLOW_COMMON),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* MCU NAVSS Invalid flow event config */
		{
			.start_resource = 0,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_INVALID_FLOW_OES),
			.host_id = HOST_ID_ALL,
		},
		/* MCU NAVSS UDMA Global event trigger */
		/* Not Applicable for TIFS */
		/* MCU NAVSS UDMA Global config */
		/* Not Applicable for TIFS */
		/* MCU NAVSS UDMA Normal capacity Rx channels */
		{
			.start_resource = 2,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 5,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 5,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 6,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 7,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 8,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 9,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 10,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 13,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 14,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 15,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 17,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 17,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 25,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 29,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 30,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 31,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 32,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 33,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 35,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 36,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 37,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 38,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 39,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 40,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 43,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		/* MCU NAVSS UDMA High capacity Rx channels */
		{
			.start_resource = 0,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_HCHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 0,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_RX_HCHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		/* MCU NAVSS UDMA Normal capacity Tx channels */
		{
			.start_resource = 2,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 5,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 5,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 6,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 7,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 8,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 9,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 10,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 11,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 12,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 13,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 14,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 15,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 17,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 17,
			.num_resource = 8,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 25,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_A72_3,
		},
		{
			.start_resource = 29,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_0_1,
		},
		{
			.start_resource = 30,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_1_1,
		},
		{
			.start_resource = 31,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_2_1,
		},
		{
			.start_resource = 32,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_C7X_3_1,
		},
		{
			.start_resource = 33,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_0,
		},
		{
			.start_resource = 35,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_0_R5_2,
		},
		{
			.start_resource = 36,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_0,
		},
		{
			.start_resource = 37,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_1_R5_2,
		},
		{
			.start_resource = 38,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_0,
		},
		{
			.start_resource = 39,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MAIN_2_R5_2,
		},
		{
			.start_resource = 40,
			.num_resource = 3,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 43,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 45,
			.num_resource = 1,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_CHAN),
			.host_id = HOST_ID_ALL,
		},
		/* MCU NAVSS UDMA High capacity Tx channels */
		{
			.start_resource = 0,
			.num_resource = 0,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_HCHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 0,
			.num_resource = 2,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMAP_0,
					RESASG_SUBTYPE_UDMAP_TX_HCHAN),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		/* MCU NAVSS Interrupt aggregator Virtual interrupts */
		{
			.start_resource = 22,
			.num_resource = 32,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_A72_2,
		},
		{
			.start_resource = 54,
			.num_resource = 64,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MCU_0_R5_0,
		},
		{
			.start_resource = 118,
			.num_resource = 4,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_MCU_0_R5_2,
		},
		{
			.start_resource = 122,
			.num_resource = 134,
			.type = RESASG_UTYPE (J784S4_DEV_MCU_NAVSS0_UDMASS_INTA_0,
					RESASG_SUBTYPE_IA_VINT),
			.host_id = HOST_ID_ALL,
		},
		/* MCU NAVSS Interrupt aggregator Global events */
		/* Not Applicable for TIFS */
	},
};
